import turtle as t
from game.enemy_msl_bhv import emsllst, stop
from ui.imgload.DeathSphider import deathsphider
import time
wn = t.Screen()
text = t.Turtle()
text.hideturtle()
text.up()
cdtext = t.Turtle()
cdtext.hideturtle()
cdtext.up()
def gameover():
    for i in emsllst:
        stop(i)
    wn.title('Game Over')
    wn.bgpic('nopic')
    wn.bgcolor('white')
    deathsphider()
    text.goto(-90,170)
    text.write('Game Over', font=('SpaceMission',30,'normal'))
    time.sleep(2)
    cdtext.sety(text.ycor()-15)
    cdtext.write('Closing in 3 seconds...')
    wn.title('3')
    time.sleep(1)
    cdtext.clear()
    cdtext.sety(cdtext.ycor()-15)
    cdtext.write('Closing in 2 seconds...')
    wn.title('2')
    time.sleep(1)
    cdtext.clear()
    cdtext.sety(cdtext.ycor()-15)
    cdtext.write('Closing in 1 seconds...')
    wn.title('1')
    time.sleep(1)
    wn.title('Closing...')
    cdtext.clear()
    cdtext.sety(cdtext.ycor()-15)
    quit()